#ifndef __DARTPUNK_INPUT_JOYSTICK__
#define __DARTPUNK_INPUT_JOYSTICK__

#include "device.h"

#define DARTPUNK_BUTTON_1    BTN_TRIGGER
#define DARTPUNK_BUTTON_2    BTN_THUMB
#define DARTPUNK_BUTTON_3    BTN_THUMB2
#define DARTPUNK_BUTTON_4    BTN_TOP
#define DARTPUNK_BUTTON_NEXT BTN_BASE4

#endif // __DARTPUNK_INPUT_JOYSTICK__

