#ifndef __DARTPUNK_INPUT_KEYBOARD__
#define __DARTPUNK_INPUT_KEYBOARD__

#include "device.h"

#define DARTPUNK_BUTTON_1    KEY_1
#define DARTPUNK_BUTTON_2    KEY_2
#define DARTPUNK_BUTTON_3    KEY_3
#define DARTPUNK_BUTTON_4    KEY_4
#define DARTPUNK_BUTTON_NEXT KEY_SPACE

#endif // __DARTPUNK_INPUT_KEYBOARD__

